package reserva_Entradas;

public enum ResultadoReserva {

	ESTADIO_COMPLETO ,
	SOCIO_INEXISTENTE ,
	SOCIO_INACTIVO ,
	SOCIO_NO_VACUNADO ,
	UBICACION_INEXISTENTE ,
	UBICACION_COMPLETA ,
	CATEGORIA_INVALIDA ,
    RESERVA_EXITOSA;




}
